name: volume_watcher_plus
description: Support ios and android real-time return system volume value, maximum volume, initial volume, support set volume.
version: 2.1.2
homepage: https://github.com/yangming1009/volume_watcher_plus

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  plugin:
    platforms:
      android:
        package: com.magugi.volume_watcher_plus
        pluginClass: VolumeWatcherPlugin
      ios:
        pluginClass: VolumeWatcherPlugin